/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package jimprimir;

import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.print.PageFormat;
import java.awt.print.Printable;


/**
 * MI JPanel tuneado
 * que implementa los métodos para imprimir
 * @author Sergio Teacher
 */
public class Impresion extends javax.swing.JPanel implements Printable {

//int PAGE_EXISTS = 0;
//int NO_SUCH_PAGE = 1;

    /**
     * Constructor
     */
    public Impresion() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        PanelInterior = new javax.swing.JPanel();
        Panel1Separador = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        Panel2 = new javax.swing.JPanel();
        txtNombre = new javax.swing.JLabel();
        jTextNombre = new javax.swing.JTextField();
        Panel4 = new javax.swing.JPanel();
        txtxDireccion = new javax.swing.JLabel();
        jTextDireccion = new javax.swing.JTextField();
        Panel5 = new javax.swing.JPanel();
        txtTelefono = new javax.swing.JLabel();
        jTextTelefono = new javax.swing.JTextField();
        Panel6 = new javax.swing.JPanel();
        txtCorreo = new javax.swing.JLabel();
        jTextCorreo = new javax.swing.JTextField();
        PanelSur = new javax.swing.JPanel();
        txtDesc = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaDesc = new javax.swing.JTextArea();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new java.awt.BorderLayout());

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Como Imprimir en JAVA");
        add(jLabel1, java.awt.BorderLayout.PAGE_START);

        PanelInterior.setBackground(new java.awt.Color(255, 255, 255));
        PanelInterior.setLayout(new javax.swing.BoxLayout(PanelInterior, javax.swing.BoxLayout.Y_AXIS));

        Panel1Separador.setBackground(new java.awt.Color(255, 255, 255));
        Panel1Separador.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 5)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 0, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("© Sergioteacher");
        Panel1Separador.add(jLabel2);

        PanelInterior.add(Panel1Separador);

        Panel2.setBackground(new java.awt.Color(255, 255, 255));

        txtNombre.setText("Nombre      ");
        Panel2.add(txtNombre);

        jTextNombre.setColumns(25);
        Panel2.add(jTextNombre);

        PanelInterior.add(Panel2);

        Panel4.setBackground(new java.awt.Color(255, 255, 255));

        txtxDireccion.setText("Dirección:  ");
        Panel4.add(txtxDireccion);

        jTextDireccion.setColumns(25);
        Panel4.add(jTextDireccion);

        PanelInterior.add(Panel4);

        Panel5.setBackground(new java.awt.Color(255, 255, 255));

        txtTelefono.setText("Teléfono:   ");
        Panel5.add(txtTelefono);

        jTextTelefono.setColumns(25);
        Panel5.add(jTextTelefono);

        PanelInterior.add(Panel5);

        Panel6.setBackground(new java.awt.Color(255, 255, 255));

        txtCorreo.setText("Correo:      ");
        Panel6.add(txtCorreo);

        jTextCorreo.setColumns(25);
        Panel6.add(jTextCorreo);

        PanelInterior.add(Panel6);

        PanelSur.setBackground(new java.awt.Color(255, 255, 255));
        PanelSur.setLayout(new javax.swing.BoxLayout(PanelSur, javax.swing.BoxLayout.Y_AXIS));

        txtDesc.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtDesc.setText("Descripción");
        PanelSur.add(txtDesc);

        jTextAreaDesc.setColumns(20);
        jTextAreaDesc.setRows(10);
        jScrollPane1.setViewportView(jTextAreaDesc);

        PanelSur.add(jScrollPane1);

        PanelInterior.add(PanelSur);

        add(PanelInterior, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Panel1Separador;
    private javax.swing.JPanel Panel2;
    private javax.swing.JPanel Panel4;
    private javax.swing.JPanel Panel5;
    private javax.swing.JPanel Panel6;
    private javax.swing.JPanel PanelInterior;
    private javax.swing.JPanel PanelSur;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextAreaDesc;
    private javax.swing.JTextField jTextCorreo;
    private javax.swing.JTextField jTextDireccion;
    private javax.swing.JTextField jTextNombre;
    private javax.swing.JTextField jTextTelefono;
    private javax.swing.JLabel txtCorreo;
    private javax.swing.JLabel txtDesc;
    private javax.swing.JLabel txtNombre;
    private javax.swing.JLabel txtTelefono;
    private javax.swing.JLabel txtxDireccion;
    // End of variables declaration//GEN-END:variables

/**
* Implementa el médodo print
*/
    @Override
    public int print (Graphics graphics, PageFormat pageFormat, int pageIndex){
        int i=0;
        if (pageIndex == 0){
            Graphics2D grafico2d = (Graphics2D) graphics;
            grafico2d.translate(pageFormat.getImageableX(), pageFormat.getImageableY());
            printAll(grafico2d); 
            i=PAGE_EXISTS;
        }else{
            i=NO_SUCH_PAGE;
        }

        return i;
    }

    /**
    * Método para vaciar los JTextField del formulario
    */
    public void limpiar() {
        jTextNombre.setText("");
        jTextDireccion.setText("");
        jTextTelefono.setText("");
        jTextCorreo.setText("");
        jTextAreaDesc.setText("");
    }


}
