/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package jimprimir;

import java.awt.print.PrinterException;
import java.awt.print.PrinterJob;
import javax.swing.JOptionPane;

/**
 *
 * @author Sergio Teacher
 */
public class VentanaImprimir extends javax.swing.JFrame {

    /**
     * Constructor de VentanaImprimir
     */
    public VentanaImprimir() {
        initComponents();
        System.out.println("Iniciando Ventana FORMULARIO");
        setBounds(0,0,450,500);
        this.setLocationRelativeTo(null);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Herramientas = new javax.swing.JToolBar();
        btnImprimir = new javax.swing.JButton();
        btnLimpia = new javax.swing.JButton();
        impresion1 = new jimprimir.Impresion();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Formulario");

        Herramientas.setBackground(new java.awt.Color(0, 255, 102));
        Herramientas.setRollover(true);

        btnImprimir.setBackground(new java.awt.Color(0, 255, 255));
        btnImprimir.setText("Imprimir");
        btnImprimir.setFocusable(false);
        btnImprimir.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnImprimir.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnImprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImprimirActionPerformed(evt);
            }
        });
        Herramientas.add(btnImprimir);

        btnLimpia.setBackground(new java.awt.Color(255, 255, 102));
        btnLimpia.setText("limpia");
        btnLimpia.setFocusable(false);
        btnLimpia.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnLimpia.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnLimpia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiaActionPerformed(evt);
            }
        });
        Herramientas.add(btnLimpia);

        getContentPane().add(Herramientas, java.awt.BorderLayout.PAGE_END);
        getContentPane().add(impresion1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

/**
* Método ejecutado en por el evento del click botón
* donde un objeto tipo PrinterJob se llama para pasarle
* al JPanel tuneado que implementa a print.
* @param evt el evento que lo activa
*/
    private void btnImprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImprimirActionPerformed
        PrinterJob job = PrinterJob.getPrinterJob();
        job.setPrintable(impresion1);

        if (job.printDialog()){
            try{
                job.print();
            }catch(PrinterException ex){
                System.out.println("e-> " + ex.getMessage());
            }
        }else{
            JOptionPane.showMessageDialog(this, "La impresión se canceló");
        }
    }//GEN-LAST:event_btnImprimirActionPerformed

    private void btnLimpiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiaActionPerformed
        impresion1.limpiar();
    }//GEN-LAST:event_btnLimpiaActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToolBar Herramientas;
    private javax.swing.JButton btnImprimir;
    private javax.swing.JButton btnLimpia;
    private jimprimir.Impresion impresion1;
    // End of variables declaration//GEN-END:variables
}
